### ISSUE TITLE
darwin01: cannot open connection to remote store 'daemon': error: unexpected end-of-file

### ISSUE THREAD

**Issue by sternenseemann** [nix-community/infra#1245]
Any store interaction fails:

```
nix-store -r /nix/store/d6dm8cpaya0nqyn8p52r6m16g3f1c4sf-y0g5zryic1ymjvvlgzbsnh0mishiyzk2-source
error: cannot open connection to remote store 'daemon': error: unexpected end-of-file
```

**Comment by sternenseemann** [comment]
Seems to be resolved!

**Comment by zowoq** [comment]
I think think there might be something wrong with this machine but not sure what exactly, I haven't seen it do this before but sometimes it just seems freeze up for a few minutes.

**Comment by zowoq** [comment]
Should be working now.

**Comment by zowoq** [comment]
I'm not sure what the actual problem was here but it probably just couldn't handle the workload very well, contributing factors were probably that it only had 16gb ram and was using a non-standard storage configuration (/nix/store on external disks in raid0).

We've now upgraded this machine to a mac mini m2 with 24gb ram and 1tb internal ssd so hopefully we'll be okay for a while.

Feel free to comment here, open another issue or ping me in the nix-community matrix room if there are any problems.

cc @toonn as you also reported problems with this machine.

cc @corngood I'm hoping this machine should be an improvement for you as well.
